zuul:
  routes:
    scst-auth:
      path: /api/auth/**
      serviceId: scst-auth
    scst-system:
      path: /api/system/**
      serviceId: scst-system-biz
    scst-component:
      path: /api/component/**
      serviceId: scst-component

