server:
  port: 5001

spring:
  application:
    name: scst-component
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

  mail:
    #邮件服务器地址
    host: smtp.sina.com
    #用户名
    username: tycoding@sina.com
    #密码
    password: ty886.
    default-encoding: UTF-8
    properties:
      mail:
        smtp.auth: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://scst-eureka:8761/eureka/
