server:
  port: 8761

spring:
  application:
    name: scst-eureka

eureka:
  instance:
    hostname: scst-eureka
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
