spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://scst-mysql:3306/scst?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai

  #邮箱
  mail:
    #邮件服务器地址
    host: smtp
    #用户名
    username: username
    #密码
    password: password
    default-encoding: UTF-8
    properties:
      mail:
        smtp.auth: true

  redis:
    #redis数据库，默认是0
    database: 1
    #redis服务器地址
    host: 127.0.0.1
    #redis服务端口，默认6379
    port: 6379
    #redis密码，默认为空
    password:

#七牛云服务
qiniu:
  access_key: ACCESS_KEY
  secret_key: SECRET_KEY
  bucket_name: BUCKETNAME
  #外链地址
  url: http://xxx/
